name: Test Request
description: We need a test for this
labels: [ "Quality Assurance" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this test request!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summarize the what you want to see tested.
      placeholder: I want to validate <this portion of our api> is tested <this way which isn't tested right now>
    validations:
      required: true
  - type: textarea
    id: why-test
    attributes:
      label: Why Test?
      description: Why is this necessary?
      placeholder: Our documented api states this should work, but I've run into times it doesn't work.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What solution do you recommend? What libraries do you recommend?
      placeholder: Because our api states that it can accept 1-9 args, we should use spock to supply data driven tests to supply said range of input.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: this is a resource I've been consuming on the subject
  - type: textarea
    id: requirements
    attributes:
      label: Test Requirements
      description: |
        Write a checklist summarizing what this test should accomplish (not how to accomplish it). All tests will adhere to our [testing standards](..blob/main/Contributing.md), there's no need to 
        reitereate any of those standards.
      placeholder: |
        - [ ] test(s) validate that a user can supply input to our api with anywhere from 1-9 args, per <this part of our api>.
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this test request!
