import { Octokit } from '@octokit/rest';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const REPO_OWNER = process.env.REPO_OWNER || 'wishonia';
const REPO_NAME = process.env.REPO_NAME || 'wishonia';

if (!GITHUB_TOKEN) {
  throw new Error(
    'GITHUB_TOKEN environment variable is required.\n' +
    'Generate a token at: https://github.com/settings/tokens/new?scopes=repo,workflow\n' +
    'Required scopes: repo (for private repos), workflow (for GitHub Actions).'
  );
}

const octokit = new Octokit({ auth: GITHUB_TOKEN });

function run(cmd: string) {
  return execSync(cmd, { encoding: 'utf-8' });
}

function hasChanges(): boolean {
  return run('git status --porcelain').trim().length > 0;
}

function getCurrentBranch(): string {
  return run('git rev-parse --abbrev-ref HEAD').trim();
}

async function createPullRequest(branch: string, title: string, body: string) {
  await octokit.pulls.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title,
    head: branch,
    base: 'main',
    body,
  });
}

function parseRoadmap(): string[] {
  const roadmapPath = path.join(process.cwd(), 'public/docs/roadmap.md');
  if (!fs.existsSync(roadmapPath)) return [];
  const content = fs.readFileSync(roadmapPath, 'utf-8');
  const matches = content.match(/- \[.\] \*\*(.+?)\*\*/g) || [];
  return matches.map(m => m.replace(/- \[.\] \*\*|\*\*/g, ''));
}

function roadmapSummary(): string {
  const items = parseRoadmap();
  if (!items.length) return 'No roadmap items found.';
  return `**Roadmap Items:**\n` + items.map(i => `- ${i}`).join('\n');
}

async function main() {
  // 1. Run code quality checks
  let checkOutput = '';
  try {
    checkOutput = run('pnpm check');
  } catch (e: any) {
    checkOutput = e.stdout || e.message;
  }

  // 2. Auto-fix lint issues if possible
  try {
    run('pnpm lint --fix');
  } catch {}

  // 3. If changes, commit and open PR
  if (hasChanges()) {
    const branch = `self-improve/auto-fixes-${Date.now()}`;
    run(`git checkout -b ${branch}`);
    run('git add .');
    run('git commit -m "chore: auto-fix lint/type issues"');
    run(`git push origin ${branch}`);
    await createPullRequest(
      branch,
      'chore: auto-fix lint/type issues',
      'This PR was automatically generated by the self-improving agent.\n\n' +
        'pnpm check output:\n' +
        '``' + checkOutput + '``\n\n' +
        roadmapSummary()
    );
    console.log('Pull request created!');
  } else {
    console.log('No changes to commit.');
  }
}

main().catch(e => {
  console.error(e);
  process.exit(1);
}); 