export const diseaseResearchSpendingProgramNames: string[] = [
  "Heart Disease",
  "Cancer (General)",
  "Lung Cancer",
  "Breast Cancer",
  "Prostate Cancer",
  "Colorectal Cancer",
  "Alzheimer\'s Disease & Dementias",
  "Diabetes (Type 1 & Type 2)",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Stroke",
  "Influenza & Pneumonia",
  "Kidney Disease (Chronic)",
  "Parkinson\'s Disease",
  "Arthritis (Rheumatoid & Osteo)",
  "HIV/AIDS",
  "Depression & Mood Disorders",
  "Anxiety Disorders",
  "Schizophrenia & Psychotic Disorders",
  "Substance Use Disorders & Addiction",
  "Chronic Liver Disease & Cirrhosis",
  "Tuberculosis",
  "Malaria",
  "Multiple Sclerosis",
  "Amyotrophic Lateral Sclerosis (ALS)",
  "Crohn\'s Disease & Ulcerative Colitis (IBD)",
  "Asthma",
  "Allergies & Autoimmune Disorders",
  "Osteoporosis",
  "Vision Loss & Eye Disease (e.g., Glaucoma, Macular Degeneration)",
  "Hearing Loss",
  "Traumatic Brain Injury (TBI)",
  "Spinal Cord Injury",
  "Sepsis",
  "Antimicrobial Resistance",
  "Rare Diseases (General)",
  "Pediatric Cancer",
  "Sickle Cell Disease",
  "Cystic Fibrosis",
  "Muscular Dystrophy",
  "Down Syndrome",
  "Autism Spectrum Disorder",
  "COVID-19 & Future Pandemic Preparedness",
  "Zika Virus & Other Arbovirus",
  "Ebola Virus",
  "Chronic Pain Management",
  "Sleep Disorders",
  "Infertility",
  "Endometriosis",
  "Polycystic Ovary Syndrome (PCOS)",
  "Thyroid Disorders",
]; 