export const illegalDrugSpendingProgramNames: string[] = [
  "Federal Cannabis Eradication & Interdiction",
  "Cocaine Trafficking Disruption Task Forces",
  "Heroin Enforcement Initiatives",
  "Fentanyl Trafficker Arrest Task Force",
  "Methamphetamine Distribution Network Arrests",
  "MDMA (Ecstasy) Trafficking Investigations",
  "LSD/Hallucinogens Trafficking Investigations",
  "Illicit Prescription Drug Trafficking Enforcement",
  "Border Security for Drug Seizures",
  "IRS - Drug Organization Financial Investigations",
  "Marijuana Flower (THC)",
  "Hashish & Hash Oil",
  "High-Potency Cannabis Concentrates (Wax, Shatter)",
  "Synthetic Cannabinoids (K2, Spice, AB-FUBINACA)",
  "Powder Cocaine",
  "Crack Cocaine",
  "Methamphetamine (Crystal, Ice)",
  "Amphetamine Sulfate (Speed)",
  "Diverted Adderall & Dexedrine",
  "Mephedrone (4-MMC / Bath Salts)",
  "Methylone (bk-MDMA / Bath Salts)",
  "α-PVP (Flakka / Bath Salts)",
  "α-PHP & α-PA (Synthetic Cathinones)",
  "N-ethylpentylone",
  "Illicit Fentanyl Analogs (Carfentanil, Acetylfentanyl)",
  "Diverted Oxycodone (OxyContin, Percocet)",
  "Diverted Hydrocodone (Vicodin, Norco)",
  "Diverted Hydromorphone (Dilaudid)",
  "Diverted Morphine & Codeine",
  "Diverted Methadone & Buprenorphine (Suboxone)",
  "Opium (Raw & Cooked)",
  "Kratom (Mitragynine)",
  "Illicit Alprazolam (Xanax)",
  "Illegal Clonazepam (Klonopin)",
  "Unlawful Diazepam (Valium)",
  "Illicit Lorazepam (Ativan)",
  "Designer Benzodiazepines (Etizolam, Flubromazolam)",
  "Illegal Phenobarbital & Secobarbital",
  "GHB & GBL",
  "Illicit Carisoprodol (Soma)",
  "Illegal Chloral Hydrate",
  "Illegal Psilocybin Mushrooms",
  "Mescaline (Peyote, San Pedro)",
  "DMT & Ayahuasca",
  "2C-B, 2C-I, 2C-E Phenethylamines",
  "25I-NBOMe & Related NBOMe Series Drugs",
  "Illegal Ketamine",
  "PCP (Phencyclidine)",
  "Misused DXM (Dextromethorphan)",
  "Nitrous Oxide (Whippets)",
  "Misused Solvents & Propellants (Toluene, Butane)",
  "Amyl/Isobutyl Nitrite (Poppers)",
  "Inhalants (Model Glue, Correction Fluid)",
  "Ibogaine",
  "Salvia Divinorum (Salvinorin A)",
  "DOM (STP) & DOx Family Designer Drugs",
  "Illicit Tryptamines (5-MeO-DMT, 4-AcO-DMT)",
  "Novel Lysergamides (AL-LAD, 1P-LSD)",
  "Benzimidazole Opioids (Isotonitazene, Metonitazene)",
  "Illicit Anabolic Steroids (Testosterone, Trenbolone)",
  "Illicit SARMs",
]; 